# fly.toml app configuration file generated for mmc2jira on 2023-11-19T11:50:56+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mmc2jira"
primary_region = "syd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "mmc2jira"
  destination = "/data"
