name: Build and deploy Node.js app to Azure Web App - mmc2jira

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'mmc2jira'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'     

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main

    - name: 'Login to Azure Services'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }} 
    
    - name: 'npm install, build, and test'
      run: |
        npm install
      working-directory:  ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
                    
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
